version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: metrics
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metrics-service:
    build: .
    container_name: metrics-service
    command: ["node", "build/service-app.js"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: supersecret
      DB_NAME: metrics
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  pgdata:
  grafana-storage:
